collections:
  localResources:
    output: true
  onlineResources:
    output: true
  sass:
    sass_dir: /assets/css

url: "https://techoutreachhi.org/"
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false
